steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - concisely
  - --region=${_LOCATION}
  - --source=.
  - --trigger-http
  - --runtime=python
  - --allow-unauthenticated
  - --set-env-vars=OPENAI_API_KEY=${_OPENAI_API_KEY},OPENAI_API_BASE=${_OPENAI_API_BASE},OPENAI_MODEL=${_OPENAI_MODEL},MAX_TOKENS=${_MAX_TOKENS}